const BASE='./';
const STORAGE_KEY='gaycast-pwa-v1';
const VERIFIED_GAY=[
  ['Gay0Day','https://gay0day.com/search/{query}/'],
  ['MachoTube','https://www.machotube.tv/search/{query}'],
  ['GayPornArchive','https://gaypornarchive.com/search/{query}/'],
  ['GayPornPlanet','https://gaypornplanet.com/search/{query}/'],
  ['SpankBang Gay','https://spankbang.com/s/{query}%20gay/1/'],
  ['BarebackBastards','https://barebackbastards.com/search/video/?s={query}']
];
const VERIFIED_GENERAL=[
  ['XVideos','https://www.xvideos.com/?k={query}&p=0'],
  ['Eporner','https://www.eporner.com/search/{query}/1/'],
  ['HQPorner','https://hqporner.com/?q={query}'],
  ['CamWhores','https://www.camwhores.tv/search/{query}/'],
  ['SunPorno','https://www.sunporno.com/search/{query}/'],
  ['FreeOnes','https://www.freeones.com/search?q={query}']
];
const state=loadState(); let sessionFiles=[]; let deferredInstall=null; let toastTimer;
const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return{history:Array.isArray(raw.history)?raw.history:[],items:Array.isArray(raw.items)?raw.items:[],favorites:Array.isArray(raw.favorites)?raw.favorites:[]}}catch{return{history:[],items:[],favorites:[]}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderHistory();renderLibrary()}
function showToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
function switchTab(name){$$('.tab').forEach(b=>{const on=b.dataset.tab===name;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});$$('[data-panel]').forEach(p=>{const on=p.dataset.panel===name;p.hidden=!on;p.classList.toggle('active',on)});if(name==='player')setTimeout(()=>$('#player').focus({preventScroll:true}),0)}
function encoded(q){return encodeURIComponent(q.trim()).replace(/%20/g,'+')}
function providerUrl(template,q){return template.replaceAll('{query}',encoded(q)).replaceAll('{page}','1')}
function renderProviders(q=''){const grid=$('#providerGrid');grid.innerHTML='';if(!q){grid.innerHTML='<div class="empty-state">Provider launchers appear after a search.</div>';return}const groups=[...VERIFIED_GAY.map(x=>[...x,'gay verified']),...VERIFIED_GENERAL.map(x=>[...x,'general verified'])];groups.forEach(([name,template,label])=>{const article=document.createElement('article');article.className='provider-card';const url=providerUrl(template,q);article.innerHTML=`<div class="provider-meta"><span>${label}</span><span>↗</span></div><h3></h3><p>Open this query on the provider itself. Results remain provider-owned and are not fabricated inside GayCast.</p><a class="ghost" target="_blank" rel="noopener noreferrer">Open search</a>`;article.querySelector('h3').textContent=name;const a=article.querySelector('a');a.href=url;a.addEventListener('click',()=>showToast(`Opening ${name}`));grid.append(article)})}
function runSearch(q){q=q.trim();if(!q)return;state.history=[{q,at:Date.now()},...state.history.filter(x=>x.q.toLowerCase()!==q.toLowerCase())].slice(0,20);saveState();$('#resultsTitle').textContent=`Provider searches for “${q}”`;$('#searchState').innerHTML='<strong>Browser-safe mode:</strong> these links run the real query on each provider. Static Pages hosting cannot reliably scrape third-party HTML across origins.';renderProviders(q);$('#query').value=q}
function renderHistory(){const box=$('#historyList');if(!state.history.length){box.className='stack empty-state';box.textContent='No searches yet.';return}box.className='stack';box.innerHTML='';state.history.forEach(item=>{const row=document.createElement('div');row.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=item.q;const small=document.createElement('small');small.textContent=new Date(item.at).toLocaleString();d.append(strong,small);const actions=document.createElement('div');actions.className='row-actions';const again=document.createElement('button');again.className='ghost';again.textContent='Search';again.addEventListener('click',()=>{switchTab('search');runSearch(item.q);window.scrollTo({top:0,behavior:'smooth'})});actions.append(again);row.append(d,actions);box.append(row)})}
function renderLibrary(){const box=$('#libraryList');const all=[...sessionFiles.map((x,i)=>({...x,session:true,index:i})),...state.items.map((x,i)=>({...x,session:false,index:i}))];$('#libraryCount').textContent=all.length;if(!all.length){box.className='stack empty-state';box.textContent='Your library is empty.';return}box.className='stack';box.innerHTML='';all.forEach(item=>{const row=document.createElement('div');row.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=item.title;const small=document.createElement('small');small.textContent=item.session?'Local file · available until this tab closes':item.url;d.append(strong,small);const actions=document.createElement('div');actions.className='row-actions';const play=document.createElement('button');play.className='ghost';play.textContent='Play';play.addEventListener('click',()=>loadMedia(item));actions.append(play);if(!item.session){const fav=document.createElement('button');fav.className='iconbtn';const key=item.url;fav.textContent=state.favorites.includes(key)?'★':'☆';fav.setAttribute('aria-label',state.favorites.includes(key)?'Remove favorite':'Add favorite');fav.addEventListener('click',()=>{state.favorites=state.favorites.includes(key)?state.favorites.filter(x=>x!==key):[...state.favorites,key];saveState()});const del=document.createElement('button');del.className='iconbtn';del.textContent='×';del.setAttribute('aria-label','Remove from library');del.addEventListener('click',()=>{state.items.splice(item.index,1);state.favorites=state.favorites.filter(x=>x!==key);saveState()});actions.append(fav,del)}row.append(d,actions);box.append(row)})}
function loadMedia(item){const player=$('#player');if(player.src?.startsWith('blob:'))URL.revokeObjectURL(player.src);const src=item.file?URL.createObjectURL(item.file):item.url;player.src=src;$('#nowPlaying').textContent=item.title||'Media';switchTab('player');player.play().catch(()=>showToast('Loaded. Tap Play if the browser blocked autoplay.'))}
function playDirectUrl(){const url=$('#directUrl').value.trim();if(!/^https:\/\//i.test(url)){showToast('Use a valid HTTPS media URL.');return}loadMedia({title:new URL(url).hostname,url});const player=$('#player');const onError=()=>{showToast('Browser could not play that URL. It may be a web page or blocked media.');player.removeEventListener('error',onError)};player.addEventListener('error',onError)}
function updateNetwork(){const b=$('#networkBadge');const online=navigator.onLine;b.textContent=online?'Online':'Offline';b.classList.toggle('offline',!online)}
function init(){const terms=['muscle','vintage','bear','daddy','locker room','massage'];const chips=$('#quickTerms');terms.forEach(term=>{const b=document.createElement('button');b.type='button';b.textContent=term;b.addEventListener('click',()=>runSearch(term));chips.append(b)});$$('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$('#searchForm').addEventListener('submit',e=>{e.preventDefault();runSearch($('#query').value)});$('#clearHistory').addEventListener('click',()=>{state.history=[];saveState();showToast('Search history cleared.')});$('#filePicker').addEventListener('change',e=>{for(const file of e.target.files)sessionFiles.push({title:file.name,file});renderLibrary();showToast(`${e.target.files.length} local file${e.target.files.length===1?'':'s'} added for this session.`);e.target.value=''});$('#addUrlBtn').addEventListener('click',()=>$('#urlDialog').showModal());$('#urlForm').addEventListener('submit',e=>{e.preventDefault();const title=$('#urlTitle').value.trim(),url=$('#urlValue').value.trim();if(!title||!/^https:\/\//i.test(url)){showToast('Title and HTTPS URL are required.');return}state.items.unshift({title,url,addedAt:Date.now()});saveState();$('#urlDialog').close();e.target.reset();showToast('Saved to this browser.')});$('#playUrlBtn').addEventListener('click',playDirectUrl);window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true});updateNetwork();renderHistory();renderLibrary();renderProviders();if('serviceWorker'in navigator)navigator.serviceWorker.register(`${BASE}sw.js`).catch(()=>showToast('Offline support could not start.'))}
init();