import test from 'node:test';
import assert from 'node:assert/strict';
import {buildProviderUrl,handleRequest,parseBarebackBastardsHtml,parseGayPornArchiveHtml,parseGayPornPlanetHtml,parseMachoTubeHtml,parseSunPornoHtml,parseXVideosHtml} from '../src/index.mjs';
import contract from '../../provider-contract.json' with { type: 'json' };
const xvideos=contract.providers.find(p=>p.id==='xvideos');
test('zero-based pagination is preserved from contract',()=>{assert.equal(buildProviderUrl(xvideos,'locker room',1),'https://www.xvideos.com/?k=locker+room&p=0');assert.equal(buildProviderUrl(xvideos,'bear',3),'https://www.xvideos.com/?k=bear&p=2')});
test('search refuses arbitrary provider IDs',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=example'));assert.equal(r.status,400);assert.equal((await r.json()).error,'provider_not_allowed')});
test('search requires explicit providers',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear'));assert.equal(r.status,400);assert.equal((await r.json()).error,'providers_required')});
test('supported provider without edge parser fails honestly',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=gay0day'));assert.equal(r.status,200);const j=await r.json();assert.equal(j.reports[0].state,'ADAPTER_UNIMPLEMENTED');assert.deepEqual(j.results,[])});
test('provider listing exposes adapter readiness separately from Android support',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/providers'));const j=await r.json();const xv=j.providers.find(p=>p.id==='xvideos');const gpp=j.providers.find(p=>p.id==='gaypornplanet');const gay=j.providers.find(p=>p.id==='gay0day');assert.equal(xv.edgeAdapter,false);assert.equal(xv.edgeState,'VANTAGE_BLOCKED');assert.equal(gpp.edgeAdapter,true);assert.equal(gpp.edgeState,'READY');assert.equal(gay.edgeAdapter,false)});
test('CORS is restricted to configured PWA origin',async()=>{const yes=await handleRequest(new Request('https://edge.test/health',{headers:{origin:'https://westkitty.github.io'}}));assert.equal(yes.headers.get('access-control-allow-origin'),'https://westkitty.github.io');const no=await handleRequest(new Request('https://edge.test/health',{headers:{origin:'https://evil.example'}}));assert.equal(no.headers.get('access-control-allow-origin'),null)});

test('XVideos parser stays scoped to search title cards',()=>{const html=`<div class="mozaique"><div class="thumb-block"><div class="thumb-under"><p class="title"><a href="/video.abc123/bear_clip" title="Bear &amp; muscle">Bear</a></p></div></div><aside><a href="/video.fake/ad" title="Ad rail">Ad</a></aside></div>`;const items=parseXVideosHtml(html,xvideos);assert.deepEqual(items,[{title:'Bear & muscle',url:'https://www.xvideos.com/video.abc123/bear_clip',providerId:'xvideos',source:'XVideos'}])});
test('BarebackBastards parser accepts only numeric thumbnail result links',()=>{const p=contract.providers.find(x=>x.id==='barebackbastards');const html=`<a href="/search/photo/?s=bear">Photos</a><a href="/142/daddy-bear-fucks-hairy-ass/" title="Daddy Bear" class="thumbnail"><img></a><a href="/static/privacy/" title="Privacy" class="thumbnail">Privacy</a>`;assert.deepEqual(parseBarebackBastardsHtml(html,p),[{title:'Daddy Bear',url:'https://barebackbastards.com/142/daddy-bear-fucks-hairy-ass/',providerId:'barebackbastards',source:'BarebackBastards'}])});

test('GayPornPlanet parser accepts only dedicated video cards',()=>{const p=contract.providers.find(x=>x.id==='gaypornplanet');const html=`<a href="/channels/men" class="un-card-link" title="Channel">x</a><a href="/video/1933511-homosexual-bear.html" class="un-card-link" itemprop="url" title="homosexual Bear">x</a><a href="/video/not-numeric.html" class="un-card-link" title="Bad">x</a>`;const out=parseGayPornPlanetHtml(html,p);assert.equal(out.length,1);assert.equal(out[0].title,'homosexual Bear');assert.equal(out[0].url,'https://gaypornplanet.com/video/1933511-homosexual-bear.html')});

test('rate limiter rejects search before upstream fetch',async()=>{const env={SEARCH_RATE_LIMITER:{limit:async({key})=>{assert.equal(key,'v1-search');return {success:false}}}};const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=gaypornplanet'),env);assert.equal(r.status,429);assert.equal((await r.json()).error,'rate_limited')});

test('GayPornPlanet generic search fallback is rejected',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>({ok:true,status:200,url:'https://www.gaypornplanet.com/search/nonsense',headers:{get:()=> 'text/html'},text:async()=>'<a href="/video/1933511-bear.html" class="un-card-link" title="Bear">x</a>'});try{const r=await handleRequest(new Request('https://edge.test/v1/search?q=nonsense&providers=gaypornplanet'));const j=await r.json();assert.equal(j.reports[0].state,'QUERY_FALLBACK');assert.deepEqual(j.results,[])}finally{globalThis.fetch=old}});
test('GayPornPlanet redirected category page can produce trusted results',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>({ok:true,status:200,url:'https://www.gaypornplanet.com/category/bear',headers:{get:()=> 'text/html'},text:async()=>'<a href="/video/1933511-bear.html" class="un-card-link" title="Bear">x</a>'});try{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=gaypornplanet'));const j=await r.json();assert.equal(j.reports[0].state,'OK');assert.equal(j.results.length,1)}finally{globalThis.fetch=old}});

test('known Cloudflare vantage failures do not refetch upstream',async()=>{let calls=0;const old=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw new Error('should not fetch')};try{for(const [id,state] of [['xvideos','VANTAGE_BLOCKED'],['barebackbastards','VANTAGE_TIMEOUT']]){const r=await handleRequest(new Request(`https://edge.test/v1/search?q=bear&providers=${id}`));const j=await r.json();assert.equal(j.reports[0].state,state);assert.deepEqual(j.results,[])}assert.equal(calls,0)}finally{globalThis.fetch=old}});

test('GayPornArchive parser accepts only dedicated gallery result links',()=>{const p=contract.providers.find(x=>x.id==='gaypornarchive');const html=`<a class="js-gallery-link" href="/2478261/very-white-chap-bangs-bearded-chap/" data-gallery-id="2478261" title="Very White chap bangs Bearded chap">x</a><a class="js-gallery-link" href="${'${video.galleryUrl}'}" data-gallery-id="1" title="${'${video.title}'}">x</a><a href="/static/privacy/" title="Privacy">x</a>`;const out=parseGayPornArchiveHtml(html,p);assert.equal(out.length,1);assert.equal(out[0].url,'https://gaypornarchive.com/2478261/very-white-chap-bangs-bearded-chap/')});
test('GayPornArchive unrelated fallback titles are rejected',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>({ok:true,status:200,url:'https://gaypornarchive.com/search/qzxqzxqzx987/',headers:{get:()=> 'text/html'},text:async()=>'<a class="js-gallery-link" href="/1234/default-listing/" data-gallery-id="1234" title="Default Listing">x</a>'});try{const r=await handleRequest(new Request('https://edge.test/v1/search?q=qzxqzxqzx987&providers=gaypornarchive'));const j=await r.json();assert.equal(j.reports[0].state,'QUERY_FALLBACK');assert.deepEqual(j.results,[])}finally{globalThis.fetch=old}});

test('MachoTube parser accepts only dedicated movie result links',()=>{const p=contract.providers.find(x=>x.id==='machotube');const html=`<a class="js-gallery-stats js-gallery-link" href="/movies/927560/sample-bear-clip" title="Sample Bear Clip">x</a><a class="js-gallery-link" href="{{ thumbLink }}" title="{{ title }}">x</a><a href="/search/bear?cats=2016" title="Filter">x</a>`;const out=parseMachoTubeHtml(html,p);assert.equal(out.length,1);assert.equal(out[0].url,'https://www.machotube.tv/movies/927560/sample-bear-clip')});
test('MachoTube unrelated fallback titles are rejected',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>({ok:true,status:200,url:'https://www.machotube.tv/search/qzxqzxqzx987',headers:{get:()=> 'text/html'},text:async()=>'<a class="js-gallery-link" href="/movies/1234/default-listing" title="Default Listing">x</a>'});try{const r=await handleRequest(new Request('https://edge.test/v1/search?q=qzxqzxqzx987&providers=machotube'));const j=await r.json();assert.equal(j.reports[0].state,'QUERY_FALLBACK');assert.deepEqual(j.results,[])}finally{globalThis.fetch=old}});

test('SunPorno parser accepts only dedicated result cards',()=>{const p=contract.providers.find(x=>x.id==='sunporno');const html=`<a class="item drclass" href="https://www.sunporno.com/v/32492/beautiful-blowjob-by-aislin-for-a-teddy-bear-grey-strapon/" title="Porn VideosBeautiful blowjob by Aislin for a teddy bear Grey, strapon">x</a><a href="https://www.sunporno.com/categories/" title="Categories">x</a>`;const out=parseSunPornoHtml(html,p);assert.deepEqual(out,[{title:'Beautiful blowjob by Aislin for a teddy bear Grey, strapon',url:'https://www.sunporno.com/v/32492/beautiful-blowjob-by-aislin-for-a-teddy-bear-grey-strapon/',providerId:'sunporno',source:'SunPorno'}])});
