import test from 'node:test';
import assert from 'node:assert/strict';
import {buildProviderUrl,handleRequest,parseBarebackBastardsHtml,parseGayPornPlanetHtml,parseXVideosHtml} from '../src/index.mjs';
import contract from '../../provider-contract.json' with { type: 'json' };
const xvideos=contract.providers.find(p=>p.id==='xvideos');
test('zero-based pagination is preserved from contract',()=>{assert.equal(buildProviderUrl(xvideos,'locker room',1),'https://www.xvideos.com/?k=locker+room&p=0');assert.equal(buildProviderUrl(xvideos,'bear',3),'https://www.xvideos.com/?k=bear&p=2')});
test('search refuses arbitrary provider IDs',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=example'));assert.equal(r.status,400);assert.equal((await r.json()).error,'provider_not_allowed')});
test('search requires explicit providers',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear'));assert.equal(r.status,400);assert.equal((await r.json()).error,'providers_required')});
test('supported provider without edge parser fails honestly',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=gay0day'));assert.equal(r.status,200);const j=await r.json();assert.equal(j.reports[0].state,'ADAPTER_UNIMPLEMENTED');assert.deepEqual(j.results,[])});
test('provider listing exposes adapter readiness separately from Android support',async()=>{const r=await handleRequest(new Request('https://edge.test/v1/providers'));const j=await r.json();const xv=j.providers.find(p=>p.id==='xvideos');const gay=j.providers.find(p=>p.id==='gay0day');assert.equal(xv.edgeAdapter,true);assert.equal(gay.edgeAdapter,false)});
test('CORS is restricted to configured PWA origin',async()=>{const yes=await handleRequest(new Request('https://edge.test/health',{headers:{origin:'https://westkitty.github.io'}}));assert.equal(yes.headers.get('access-control-allow-origin'),'https://westkitty.github.io');const no=await handleRequest(new Request('https://edge.test/health',{headers:{origin:'https://evil.example'}}));assert.equal(no.headers.get('access-control-allow-origin'),null)});

test('XVideos parser stays scoped to search title cards',()=>{const html=`<div class="mozaique"><div class="thumb-block"><div class="thumb-under"><p class="title"><a href="/video.abc123/bear_clip" title="Bear &amp; muscle">Bear</a></p></div></div><aside><a href="/video.fake/ad" title="Ad rail">Ad</a></aside></div>`;const items=parseXVideosHtml(html,xvideos);assert.deepEqual(items,[{title:'Bear & muscle',url:'https://www.xvideos.com/video.abc123/bear_clip',providerId:'xvideos',source:'XVideos'}])});
test('BarebackBastards parser accepts only numeric thumbnail result links',()=>{const p=contract.providers.find(x=>x.id==='barebackbastards');const html=`<a href="/search/photo/?s=bear">Photos</a><a href="/142/daddy-bear-fucks-hairy-ass/" title="Daddy Bear" class="thumbnail"><img></a><a href="/static/privacy/" title="Privacy" class="thumbnail">Privacy</a>`;assert.deepEqual(parseBarebackBastardsHtml(html,p),[{title:'Daddy Bear',url:'https://barebackbastards.com/142/daddy-bear-fucks-hairy-ass/',providerId:'barebackbastards',source:'BarebackBastards'}])});

test('GayPornPlanet parser accepts only dedicated video cards',()=>{const p=contract.providers.find(x=>x.id==='gaypornplanet');const html=`<a href="/channels/men" class="un-card-link" title="Channel">x</a><a href="/video/1933511-homosexual-bear.html" class="un-card-link" itemprop="url" title="homosexual Bear">x</a><a href="/video/not-numeric.html" class="un-card-link" title="Bad">x</a>`;const out=parseGayPornPlanetHtml(html,p);assert.equal(out.length,1);assert.equal(out[0].title,'homosexual Bear');assert.equal(out[0].url,'https://gaypornplanet.com/video/1933511-homosexual-bear.html')});

test('rate limiter rejects search before upstream fetch',async()=>{const env={SEARCH_RATE_LIMITER:{limit:async({key})=>{assert.equal(key,'v1-search');return {success:false}}}};const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=gaypornplanet'),env);assert.equal(r.status,429);assert.equal((await r.json()).error,'rate_limited')});

test('GayPornPlanet generic search fallback is rejected',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>({ok:true,status:200,url:'https://www.gaypornplanet.com/search/nonsense',headers:{get:()=> 'text/html'},text:async()=>'<a href="/video/1933511-bear.html" class="un-card-link" title="Bear">x</a>'});try{const r=await handleRequest(new Request('https://edge.test/v1/search?q=nonsense&providers=gaypornplanet'));const j=await r.json();assert.equal(j.reports[0].state,'QUERY_FALLBACK');assert.deepEqual(j.results,[])}finally{globalThis.fetch=old}});
test('GayPornPlanet redirected category page can produce trusted results',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>({ok:true,status:200,url:'https://www.gaypornplanet.com/category/bear',headers:{get:()=> 'text/html'},text:async()=>'<a href="/video/1933511-bear.html" class="un-card-link" title="Bear">x</a>'});try{const r=await handleRequest(new Request('https://edge.test/v1/search?q=bear&providers=gaypornplanet'));const j=await r.json();assert.equal(j.reports[0].state,'OK');assert.equal(j.results.length,1)}finally{globalThis.fetch=old}});
